class IntentTypes:

    GREETING = "GREETING"

    ASK_AI_NAME = "ASK_AI_NAME"
    ASK_AI_VERSION = "ASK_AI_VERSION"
    ASK_AI_LANGUAGE = "ASK_AI_LANGUAGE"

    REMEMBER_USER_NAME = "REMEMBER_USER_NAME"
    ASK_USER_NAME = "ASK_USER_NAME"

    UNKNOWN = "UNKNOWN"